### ISSUE TITLE
No any progress about IOS and Keys tool

### ISSUE THREAD

**Issue by cryptomate** [Coinomi/coinomi-android#105]
For long time no any progress with IOS version.
Also, Without mnemonic tool coinomi not wallet,but online service.
At this time tool support only about 10 currency.
No any progress, with add more coins to the tool.
Without support all coins in wallet in this tool, coinomi can't  move forward, no matters how many coins add to wallet, they unusable.

**Comment by GeorgeKimionis** [comment]
This is not the right place to express your opinion. Invalid issue, closing.
