### ISSUE TITLE
Crashes while sweeping private key

### ISSUE THREAD

**Issue by agulab** [Coinomi/coinomi-android#109]
I had the same crash twice, with the same BTC private key. Firstly I input it char by char with the keyboard myself. Second time I scanned it from a QR code. Both times it asked me to wait while private key was imported, and after some seconds it crashed (I sent both reports from Android).
Just in case, note that the address being scanned contains only 0.0001BTC.
Android v6.0
Coiniomi v1.6.3

**Comment by agulab** [comment]
I tried again a third time and saw that it crashes after "Loading balance", when the message "Creating transaction" appears

**Comment by rocketman1337345** [comment]
Can confirm this is still a bug. Tried on Android 6 and 7 with Coinomi 1.7.2. Fucking bug cost me thousands 😠

**Comment by tzarebczan** [comment]
So it sweeps the wallet and doesn't give you the coins?

**Comment by jku** [comment]
Seeing the same thing (1.7.3 on android 6.0.1) although the whole app does not crash: After inputting a private key and clicking next It says "creating transaction" and immediately goes back to the main view (I suppose it should ask me about transaction fees at this point). Nothing gets added to wallet (and no transactions seem to appear on the chain)

**Comment by chrisjh0001** [comment]
Exactly the same here. Instead of going to the "Confirm" page after briefly saying "creating transaction", it head straight back to the Coinomi wallet balance and nothing is changed. As far as I can see it isn't actually creating the transaction at all and the allegedly swept wallet's contents appear to remain in situ. Anyone got any clues on this?

**Comment by jgeewax** [comment]
:+1: to this. This is super scary given that we don't know for sure whether there's something bad happening here....

This was fine 4 days ago :-(

**Comment by aphexmunky** [comment]
Getting the same issue here. v1.7.3

Funds aren't moved though so unsure how @rocketman1337345 could lose money?

**Comment by chrisjh0001** [comment]
And now Coinomi's "27/7 support team" have stopped responding to support tickets. Mine's been lodged with them for 4 days now. Not a peep. Time for us to clear out and move on I think. Anyone know of another BCH wallet with a "sweep" facility?

**Comment by chrisjh0001** [comment]
And now Coinomi's "27/7 support team" have stopped responding to support tickets. Mine's been lodged with them for 4 days now. Not a peep. Time for us to clear out and move on I think. Anyone know of another BCH wallet with a "sweep" facility?

**Comment by cscott** [comment]
On Aug 25, 2017 4:56 AM, "chrisjh0001" <notifications@github.com> wrote:

Anyone know of another BCH wallet with a "sweep" facility?

I ended up using electron cash.

**Comment by aphexmunky** [comment]
changelog reports this is fixed now and i've confirmed this is working in v1.7.4

**Comment by erasmospunk** [comment]
This is fixed now.
