### ISSUE TITLE
Dash's 8/21 Hard Fork + Out-of-date Coinomi == Fucked $2,000 Transaction [urgent!!]

### ISSUE THREAD

**Issue by hopeseekr** [Coinomi/coinomi-android#110]
HELP!!!

Context: https://www.reddit.com/r/dashpay/comments/4ywa17/hard_fork_my_2000_equiv_transaction_is_lost/

**Comment by GeorgeKimionis** [comment]
You haven't lost any coins, your funds are 100% safe and will be reflected in your client as soon as we finish updating our back-end servers. Closing ticket for vulgar language.

**Comment by hopeseekr** [comment]
No 30ish year-old is offended by the word "fuck". Let's be serious and not so self-righteous.

**Comment by agulab** [comment]
It wasn't a HARD FORK at all. As people have been explaining to you in the reddit post you linked:
> Two blocks were found almost at the same time by different protocol versions. Since "enough" miners and nodes ran the deprecated version, the "wrong" block wasn't rejected but created an own chain.

So if need to spend those 144DASH urgently, you could open your wallet using your recovery phrase in another client and your Dash would be there.

**Comment by GeorgeKimionis** [comment]
@agulab thanks for your input.

@hopeseekr we have just finished updating our back-end servers, everything will be in place as soon as they catch up with the latest blocks, it shouldn't take more than a few hours. How much would you be willing to pay for Coinomi if you could have a better (according to you) customer service?

**Comment by hopeseekr** [comment]
I would definitely pay you up to 10% of the issue, or $200 for immediate expedited service.

I further have a great wish for a *purchased* wallet with 1) realtime customer service during normal business hours (UK business hours are fine, I can adapt), 2) expedited direct email support 24x7, 3) real-world contractual Service Level Agreements (SLAs) regarding such things as changes to coins that require immediate Coinomi support to fix (e.g., Ethereum fork, Dash 'hiccup', etc.). 

I do not mind, and see the benefits of, paying for separate SLA contracts for each cryptocurrency I choose.

Personally, since I am fairly high roller in Bitcoin and Dash (25+ BTC/month), I would be willing to pay somewhere between $100 and $1,500 per year for such a wallet and services, depending mainly on the support level. 

**I absolutely detest how with every free wallet -I- am the product, and never qualify for any direct support.**

I just gave you guys a great business plan. You should probably open this ticket and have the CEO thank me as your revenue triples.

**Comment by hopeseekr** [comment]
The PR from Coinomi's official responses to both myself and the client have tarnished not just Coinomi but Dash in the eyes of anyone who sees that this happened because of two miners mining the same block at the same time (pretty common in cryptocurrencies!) and that it has been over 72 hours and either no response [to my client] or a Closed response with an unknown ETA in my case, while no one in the Dash community seems to care.

If this were a more established cryptocoin, I would imagine quite the uproar and major price devaluation, but Dash is up 4% since. This seems to suggest that it is almost universally a Coinomi problem.
