### ISSUE TITLE
Gridcoin integration

### ISSUE THREAD

**Issue by grctest** [Coinomi/coinomi-android#116]
Hey,

The Gridcoin community paid for integration into Coinomi months ago and no estimate for integration has been provided, please provide an estimated release time.

Many users are not happy with the lack of a response on this matter, they were under the impression that Coinomi was actively adding new cryptocurrencies, especially since payment has already been made.

If no work has been committed & there are no plans to integrate Gridcoin in the near future then a refund would be optimal.

Coinomi cryptocointalk thread: https://cryptocointalk.com/topic/46477-gridcoin-coinomi-android-wallet-integration/#entry224092

Thanks.

**Comment by GeorgeKimionis** [comment]
Gridcoin has already been integrated as also stated on twitter and is going live next week, thanks for your patience.

**Comment by grctest** [comment]
Thanks

**Comment by GeorgeKimionis** [comment]
Gridcoin is now live in v1.6.4 beta. 

Testers' version: https://play.google.com/apps/testing/com.coinomi.wallet
