### ISSUE TITLE
HD recovery problem: password != BIP39 passphrase ?

### ISSUE THREAD

**Issue by molecular** [Coinomi/coinomi-android#122]
I just werstled with a (to me) very strange problem.

I wanted to access the bitcoin and potcoin keys managed by coinomi android wallet using the bip39 tool https://github.com/erasmospunk/bip39. After adding Potcoin to it (see my pull request https://github.com/erasmospunk/bip39/pull/1) I discovered it would generate the wrong keys (for both bitcoin and potcoin)

I played around with the derivation path for a long time (turns out info here: https://onedrive.live.com/view.aspx?resid=584F122BA17116EE!313&app=Excel and bip44 derivation path construction is correct for coinomi wallet) before discovering that apparently the "wallet password" is not identical to the "bip39 passphrase".

I was of that impression because the faq states:

> I have forgotten my app password, is it possible to recover it?
> It is possible if you haven't enabled BIP39 passphrase with your recovery phrase. To test it, use this tool with your recovery phrase and look if the addresses in the "Derived Addresses" section match the addresses in your wallet. If this is the case you can restore your wallet with your recovery phrase and set a new password. If however the addresses don't match, you will need to **remember your password and enter it to the "BIP39 Passphrase (optional)" field**.
> 

**So my question: is the "wallet password" identical to the "BIP39 Passphrase"?**

If yes: why do I have to remove the last character from my wallet password to make it work as BIP39 passhrase (this is strange in itself, but it's possible I used xxxy as password and xxx as BIP39 passphrase)

If no:
 * why does the FAQ give the impression these 2 are the same?
 * why is it impossible to display the BIP39 passphrase in the wallet app using the password (it *must* be stored somewhere in this case, otherwise the wallet wouldn't be able to generate the correct keys)

**Comment by erasmospunk** [comment]
They are not the same.

The "wallet password" is used only to encrypt the derived master and account private keys. The BIP39 passphrase is only used to derive master private key in conjunction to the recovery phrase. Check the [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#From_mnemonic_to_seed) spec for more details.

The BIP39 passphrase is not saved, only used when restoring the wallet to generate the master private key. Every account private key is generated from the master private key.

The FAQ is wrong, thanks for pointing it out!

If you still have difficulty with the recovery phrase tool, let us know.

**Comment by molecular** [comment]
Ok, I understand.

Very good. No, I have no problems with the tool, works fine now.

Thanks for your awesome work, btw.
