### ISSUE TITLE
Could not load exchange rates.

### ISSUE THREAD

**Issue by bariscaliskan** [Coinomi/coinomi-android#124]
In the live build, I am having an issue with exchange rates. I can see my coins but I can't see their worth. Samsung Galaxy S6 - 6.0.1
Thanks.

**Comment by adilsonsouza** [comment]
My galaxy s6 same problem.

**Comment by adilsonsouza** [comment]
And not update quotation.

**Comment by erasmospunk** [comment]
Transient DNS issue. Reopen if it persists.

**Comment by bariscaliskan** [comment]
I have reopened it before writing here of course.
But problem solved after 1 week of no exchange rates now.
I don't know how.
