### ISSUE TITLE
Coinomi is no longer open source

### ISSUE THREAD

**Issue by Redsandro** [Coinomi/coinomi-android#132]
@GeorgeKimionis changed the license from "CC **Share-Alike**" (A.K.A. the right to create derivative works) to ["A (..) license is granted (..) **without the rights to create derivative works**"](https://github.com/Coinomi/coinomi-android/commit/92aaf206c14c971f3455e055edbea418cad3520f). As such, collaborators may no longer download, modify, and publish their version (fork) back to the community, and Coinomi is no longer free (as in speech).

The third rule of the [Open Source definition](https://opensource.org/docs/osd) states:

> The license must allow modifications and derived works, and must allow them to be distributed under the same terms as the license of the original software.

CC and particularly NC were already fishy, but now the liberty is completely gone. I don't think it's fair to market Coinomi as Open Source any longer.

![image](https://cloud.githubusercontent.com/assets/1702193/22177224/e4e9636e-e019-11e6-9ea3-4d744517e0a8.png)

**Comment by GeorgeKimionis** [comment]
We do what we have to do to protect our users and our brand. Coinomi is a **free** wallet and its source code is **open** for everyone to review, but if you're asking us to allow just about anyone to create malicious clones of our wallet and steal users' funds and give up any power to go after these scammers and their works then no, it's not going to happen. On top of that, I would strongly recommend you to be very careful when making unsubstantiated accusations in public such as that Coinomi Wallet _"is no longer free"_ and that it was governed by a _"fishy"_ license, as these could imply direct defamation of our firm.

**Comment by oktoshi** [comment]
Coinomi has always behaved in a real professional way, the code is still available for review, hence providing the users with transparency and security, all their changes are in regards to evolving and protecting their users, where they do a great job.

**Comment by Redsandro** [comment]
Such threatening language to a former community member who helped add coins to Coinomi.

I understand your point. But when you drive a porsche - with good reason - you just can't go around and claim you're driving a ferrari. As a fan of open source software, I'm just pointing out that this is adding to the confusion.

Oh and feel free to frame. I 'substantiated' my 'claims' rather clearly. However, I add another explanatory link, changed the title, and replaced the word 'fishy' with 'problematic' in order to satisfy the interests that are the foundation of your threats.

**Comment by GeorgeKimionis** [comment]
Descriptions updated.
