### ISSUE TITLE
Will this software be further developed?

### ISSUE THREAD

**Issue by EtherTyper** [Coinomi/coinomi-android#137]
No commits have been made since November, where a combination of GPLv3/CC-BY-NC-SA-4.0 for the wallet and Apache 2.0 for core code was swapped out for a non-sublicensable EULA. Is there any plans to further develop the app under this **highly restrictive** license, or has the project been abandoned altogether?

Thanks,
Eli Bradley

**Comment by GeorgeKimionis** [comment]
Hi Eli, the app is being developed on a full-time basis by our team so no, Coinomi has not been abandoned. The new license is there to protect our users from scammers who kept on stealing users' funds by cloning our app and hurting our reputation while there was nothing we could do about it.
