### ISSUE TITLE
Coinomi lacking from bitcoin.org/en/choose-your-wallet

### ISSUE THREAD

**Issue by dandv** [Coinomi/coinomi-android#146]
The link to "publicly reviewed" at https://coinomi.com/

![image](https://cloud.githubusercontent.com/assets/33569/25289480/a2b13ade-267e-11e7-8eb7-1c63067d582f.png)

... points to https://bitcoin.org/en/choose-your-wallet, which doesn't list Coinomi:

![image](https://cloud.githubusercontent.com/assets/33569/25289513/c4fc4c64-267e-11e7-8a66-180d41d4f5b6.png)

**Comment by GeorgeKimionis** [comment]
That's interesting. Coinomi should be visible under the Android section, according to the source code:

![source](https://cloud.githubusercontent.com/assets/574301/25291798/2dae79d2-26dc-11e7-8772-920222199f9f.jpg)

This is the merged PR to bitcoin.org: https://github.com/bitcoin-dot-org/bitcoin.org/pull/780

**Comment by GeorgeKimionis** [comment]
https://github.com/bitcoin-dot-org/bitcoin.org/pull/1592
