### ISSUE TITLE
Pivx and stratis Balance missing

### ISSUE THREAD

**Issue by akoyonip** [Coinomi/coinomi-android#148]
Hi hello coinomi support. I have a problem in my wallet , when I open the app my Pivx Balance missing. 
And try to clear data . And restore my data using p-phrase . When is finished sync, no pivx balance and stratis coin empty.

This is my Pivx wallet use every day
[removed]

My public key:

[removed]

**Comment by erasmospunk** [comment]
Please don't post your addresses and public keys to preserve your privacy.

For any issue you have, please contact support@coinomi.com
