### ISSUE TITLE
Missing Deposits

### ISSUE THREAD

**Issue by usmarine2141** [Coinomi/coinomi-android#150]
I am missing deposits to my ZCASH wallet. 1 was generated over 4 hours ago, with 90+ confirms

https://explorer.zcha.in/transactions/7d652e4d269fd65b8fb001a667ebfde8c786bb4ccfe7df2f470006562a649440

This one having over 10 right now, neither show up in my wallet, both were deposited today 4/28/17 i havent had a deposit since yesterday. 

https://explorer.zcha.in/transactions/94bd978d853c420ac9a53964ca53f806b37525f50983f109887f9e29a067236d

**Comment by GeorgeKimionis** [comment]
[A ticket](https://support.coinomi.com/scp/tickets.php?id=4850) was opened half an hour ago with these details. This isn't the right place to ask for help.

**Comment by usmarine2141** [comment]
i understand, i sent a ticket in a few days ago as well, and havent heard anything back. Appears im not able to send anything out of my zcash wallet. errors when trying to move it out.

**Comment by usmarine2141** [comment]
When will the ticket get a response, hey i got your ticket, were looking
into it, somthing?

**Comment by erasmospunk** [comment]
@usmarine2141 there was a DOS attack on Zcash nodes, updated to a fixed version.

**Comment by usmarine2141** [comment]
thanks for the response, i uninstalled the app, and re-installed and restored my keys,... all working now 

keep up the good work
