### ISSUE TITLE
set fee to .002 

### ISSUE THREAD

**Issue by usmarine2141** [Coinomi/coinomi-android#158]
I manually set my fee to .002 and would of thought putting it up for ~3 bucks would get my bitcoin to me faster, WRONG!!!!!

5eebe51c0a7e38b2027e43d677fa0e5b22e28a1884577fdb410d955a440e5833

What is the deal with this?

**Comment by GeorgeKimionis** [comment]
This isn't the right place to ask for help, please forward your issue to: support@coinomi.com

**Comment by usmarine2141** [comment]
Y'all don't answer!!!!!

**Comment by usmarine2141** [comment]
Here is the only place to get help
