### ISSUE TITLE
Bitcoins stuck! Are your sources working?

### ISSUE THREAD

**Issue by WladCooper** [Coinomi/coinomi-android#167]
I think you made a beautiful project. And I was curious how it works.
I have downloaded sources. Built. Run.
First time it was cool. I sent BTC to few wallets.
Balance was confirmed on both wallets, everything was fine.
But next time when I was trying to send btc from one wallet to another everything get stuck. 
No transaction confirmations. Why is that?!!

What to do with my BTC balance? Will it stuck too if try to send BTC to desktop wallet?
![untitled-1](https://cloud.githubusercontent.com/assets/28909652/26379397/c7e6abba-4021-11e7-91a8-e72f8455e8a9.png)

**Comment by GeorgeKimionis** [comment]
You probably set the tx fees too low. The fastest and cheapest tx fee at the moment is 360 satoshis/byte. For dynamic fees download the compiled app from Play Store.

**Comment by WladCooper** [comment]
Why did you close the issue? I still don't know what to do with my BTC.

Can I somehow rebroadcast transaction with higher fee using coinomi? If I can't what you suggest me to do with my 0.31BTC? Just wait? 
It has already been ten days.
