### ISSUE TITLE
Unable to send dgb funds

### ISSUE THREAD

**Issue by johnatanlopes** [Coinomi/coinomi-android#179]
I can not exchange money or even move to another wallet. Returns error. Follow screenshots attached 
![1](https://user-images.githubusercontent.com/12385171/27011834-0da8cf8e-4e9b-11e7-9ee9-1c707d359b02.jpg)
![2](https://user-images.githubusercontent.com/12385171/27011835-1630bbee-4e9b-11e7-8380-c395a6c3e40c.jpg)

**Comment by GeorgeKimionis** [comment]
https://twitter.com/CoinomiWallet/status/876746906382336000
