### ISSUE TITLE
desktop version

### ISSUE THREAD

**Issue by bearsylla** [Coinomi/coinomi-android#18]
I love the android wallet so much. I wonder if there is any chance that the wallet be ported to desktop? maybe something like multibit?

**Comment by misiek08** [comment]
+1

No single multi-currency app for Win or/and Linux available, that's sad. I need something light with at least jsonRPC access.

**Comment by GeorgeKimionis** [comment]
@crispybear and @misiek08, thanks for your input. A desktop version of the Coinomi Wallet is already part of our plans. We do our best to keep up with all community demands. Hopefully we will be able to have a desktop version soon. In the meantime please share your thoughts on what features you would like it to have (eg a JSON-RPC API).

**Comment by misiek08** [comment]
For me a must-be is JSON-RPC API, because I have now a project accepting many payments, I wonna keep wallets on my side and running wallets for 14 currencies takes over 5-6G of RAM.... I did a small rewrite of few wallets, but it's not enough.

**Comment by crispybear** [comment]
It would be great if there is a Private key sweeping feature, Many of the wallets only support privatekey importing, which is quite annoying.

Also, it would be a bonus if there is staking support for POS coins. (i know this is difficult :p)

**Comment by btsfav** [comment]
any news?

**Comment by OKtoshi** [comment]
While the desktop app gets released you can try BlueStacks (Easy to install and use Android for Desktop Emulator) and install coinomi like you normally would.
On suggested features it would be nice to add a 1 click button that Prints the screen (or directly the address barcode to get payment) and upload the pic to a site (imgur maybe) in a short link format for easy share across platforms/internet.

**Comment by 5thdimension** [comment]
You should use andyroid it use VM NAT etc The best android out here im pretty sure coinomi dev could use it to port the apk

**Comment by GeorgeKimionis** [comment]
Coinomi Desktops will be released soon for Windows, Linux and MacOS. Anyone wanting to give a go to the beta releases can join the #testers channel in our slack: http://slack.coinomi.net/

**Comment by ivivanov-bg** [comment]
Any update ? It's been quite some time since the lastvinfo
