### ISSUE TITLE
UASF compatibility 1 August preparations

### ISSUE THREAD

**Issue by l00pz123** [Coinomi/coinomi-android#188]
Is there going to be an update before August addressing the possibility of SF? Electrum is running simulations of two coins for weeks now. 

Maybe you could post on FB/Twitter for you users what to do and how and why?

**Comment by rwcarlsen** [comment]
Also bitcoin cash and bitcoin abc (i.e. potential hard forks) - what does coinomi plan to allow/support?

**Comment by erasmospunk** [comment]
@l00pz123 @rwcarlsen we have supported BIP148 from the beginning. We kept several electrum servers synced on the core and the BIP148 chain so in case of a permanent split we could offer the users a choice. As you may already know the activation of BIP91 removes the possibility of a BIP148 split.

Regarding the BitcoinCash launch, we will support it as an altcoin.
