### ISSUE TITLE
Desktop Version: Java error  main class in.multico.Main

### ISSUE THREAD

**Issue by Jzarecta** [Coinomi/coinomi-android#192]
I use the Desktop version on one computer but whne I tried to install it on another computer with the same linux distro I get the following error:
``` Error: Could not find or load main class in.multico.Main ```
Anyway to fix this?

**Comment by GeorgeKimionis** [comment]
Thanks for reporting this, please report this to the #testers channel in our slack as this repo is for android only.

**Comment by Jzarecta** [comment]
I dont use slack, is there a Github issue tracker for the desktop?
