### ISSUE TITLE
No Ethereum or Ethereum Classic?

### ISSUE THREAD

**Issue by onnz423** [Coinomi/coinomi-android#197]
I looked up on the code, and trued searching as well but then i realized there is no ethereum on the github repo. At least the compiled coinomi from google play features them as an option. Does anyone know where i can find a newer source that includes ETH and ETC?

**Comment by erasmospunk** [comment]
The code in this repo is an older version, we stoped publishing the code for the time being due to numerous forks that steal our work. In the future this may change though.

Regarding the Ethereum code, we have used the EthereumJ to create and sign transactions.

**Comment by onnz423** [comment]
Ah too bad, i was going to fork the repository and add https://bitcointalk.org/index.php?topic=2012213.0 to the coinomi. However i hope that on future you can make the source open again, so people can create their own forks as well for other coins than supported on the official one.

Thank you for your answer, Best Regards.
