### ISSUE TITLE
USAF FORK

### ISSUE THREAD

**Issue by usmarine2141** [Coinomi/coinomi-android#198]
What is the plan for the BTC fork? WIll yall support it? or should we move coins to another?

**Comment by erasmospunk** [comment]
The USAF (BIP148) doesn't do anything as BIP91 was activated but we do support it.

If you are referring to the BitcoinCash (BCH) launch. We are going to add support for BitcoinCash as an altcoin (different icon, symbol, etc) and you could use it to open your Bitcoin account as BitcoinCash.

In any case you control your private keys so the wallet is the best place to keep your coins if you want to get some BCH.
