### ISSUE TITLE
Could not send coins: gas limit too high

### ISSUE THREAD

**Issue by carlos-verdes** [Coinomi/coinomi-android#217]
Hello,

Trying to send ETH (0.19) to BTN changer contract (0xb626A5FacC4de1c813F5293Ec3bE31979f1D1c78) I receive all the time the next error:
Could not send coins: gas limit too high

Could you please take a look?

**Comment by radis1337** [comment]
Thanks for reporting this, please open a ticket at: https://coinomi.freshdesk.com/helpdesk
