### ISSUE TITLE
Can not recover wallet

### ISSUE THREAD

**Issue by tjgillies** [Coinomi/coinomi-android#22]
I have a recovery phrase I have used before to recover my coinomi wallet in the past but it is no longer working. The app now says 'Could not verify, word list must be multiple of three words'. The weird thing is the recovery phrase *is* a multiple of three words.

**Comment by tjgillies** [comment]
When I create a QR code of same phrase and scan it, it works..... *sigh of relief*

**Comment by erasmospunk** [comment]
@tjgillies this could a bug that you discovered. Could you try to reproduce this?

To give you an example, there was a subtle bug in older versions where if you added extra spaces between the words it would complain about unrecognized words.

When you scan the phrase as a QR it just adds it to the text field and the validation code is the same as if you wrote it by hand.

**Comment by GeorgeKimionis** [comment]
@tjgillies could you please give us a heads up on whether you were able to reproduce [this weird behavior](https://github.com/Coinomi/coinomi-android/issues/22#issue-75732409)? Thank you.

**Comment by GeorgeKimionis** [comment]
Issue has remained open for a month while no additional information was provided, closing.

**Comment by mazapayu2015** [comment]
yeah Im getting the same thing I copy everything word for word in 3 word blocks and it says the same thing could not recover....must be in multiples of 3 words.... even when it is
