### ISSUE TITLE
always gies back to "Bitcoin Test"

### ISSUE THREAD

**Issue by drakoin** [Coinomi/coinomi-android#23]
my Coinomi always goes back to the "Bitcoin Test" wallet:

Then I go through the pain of typing in the long recovery phrase, and I am in my wallet. Good.

Next time I start Coinomi, I am back in the "Bitcoin Test" wallet.

**Comment by erasmospunk** [comment]
What version are you using? There was a bug in an older version that was overwriting the wallet file when restoring.

**Comment by erasmospunk** [comment]
@drakoin did you finally solve this issue?

**Comment by GeorgeKimionis** [comment]
@drakoin could you please provide us with your wallet's version?

**Comment by GeorgeKimionis** [comment]
Not enough information.

**Comment by drakoin** [comment]
Oh, sorry.

I had used the version that I had downloaded on the same day.

Lemme have a look ...

Coinomi v1.5.14
on android 4.4.2

**Comment by erasmospunk** [comment]
Cannot reproduce this.

@drakoin can you try again to restore and if the test wallet reappears?
