### ISSUE TITLE
not receiving tx's

### ISSUE THREAD

**Issue by doged** [Coinomi/coinomi-android#29]
ok so i've got a solid compile, but the coin ive added doesnt seem to receive the tx. it does connect to the electrum server, and our electrum client does work with it. so i believe somewhere in the coinami code, its not parsing the transactions properly. i needed to add nTime to the electrum wallet to get it to receive, so i believe i need to do that here as well.
doged/electrum-doged@d319abc#diff-e8acc63b1e238f3255c900eed37254b8

any advice is appreciated, ill continue to work on this, then submit a PR when complete. thanks!

**Comment by doged** [comment]
@erasmospunk any idea? tough figuring out python to java

**Comment by doged** [comment]
i have it generating qr's and addresses properly, just cant get it to parse an incoming transaction

**Comment by erasmospunk** [comment]
If the transaction is different than a standard Bitcoin transaction, then a modification is needed to [bitcoinj](https://github.com/Coinomi/bitcoinj).

**Comment by doged** [comment]
ahhh gotcha.. i think i remember the only issue with bitcoinj interacting with our coin daemon was that our daemon only accepts lowercase, so getBalance wont work.. has to be getbalance, and so on.. but maybe its the header of the tx.. ill keep you posted and see if we can still find a way to get doged in coinami, if not though, i do appreciate the insight

**Comment by doged** [comment]
@erasmospunk is peercoin working on this wallet? because i noticed it uses bitcoinj, and bitcoinj doesnt have support for ntime, but peercoinj does..

**Comment by erasmospunk** [comment]
Coinomi uses a modified [Bitcoinj](https://github.com/Coinomi/bitcoinj)

**Comment by doged** [comment]
@erasmospunk What SDK is bitcoinj built into a jar with? not being registered yet for bip44 couldnt be the reason the wallet isnt receiving tx's, could it?

**Comment by FuzzyHobbit** [comment]
Info for building bitcoinj: https://github.com/Coinomi/bitcoinj/blob/master/README.md

Not being assigned a BIP44 index wouldn't stop transactions from working.

**Comment by doged** [comment]
@FuzzyHobbit yeah i did not think so. btw what SDK does the bitcoinj.jar need to be built with? instructions dont mention that part.

**Comment by erasmospunk** [comment]
@doged try `mvn clean install` in the `core` directory of bitcoinj.

Also, you should use the `coinomi-0.12.2` branch.

**Comment by doged** [comment]
yeah i just got it =]

**Comment by doged** [comment]
was having an issue with orchid, didnt realize i had to go into that directory sep and mvn clean install, then go back to root n clean install again.
