### ISSUE TITLE
Heads up: Darkcoin prefixes.

### ISSUE THREAD

**Issue by vertoe** [Coinomi/coinomi-android#3]
Hi, I want to update you with the latest changes in darkcoin development.
With a new core update (release pending) some address prefixes for the network changed.
Here is an overview:
- Darkcoin P2SH-Public keys version got updated to `16` (`0x10`): see https://github.com/darkcoin/darkcoin/blob/v0.11.0.x/src/chainparams.cpp#L70
- Darkcoin HD wallet prefixes (BIP32) got aligned with the implementation of pycoin to `(0x02)(0xFE)(0x52)(0xF8)` and `(0x02)(0xFE)(0x52)(0xCC)`: see https://github.com/darkcoin/darkcoin/blob/v0.11.0.x/src/chainparams.cpp#L72 and https://github.com/richardkiss/pycoin/blob/master/pycoin/networks.py#L36
- Darkcoin Multiaccount HD wallets (BIP44) prefix should be in line with the SLIP-0044 which recommends `(0x80000005)` for Darkcoin. http://doc.satoshilabs.com/slips/slip-0044.html

Could you update the public key version of p2sh addresses (wallets and redeemscripts are still using the old private key version and therefore continue working) and comment on the other two points, please? thanks!

if you have any questions, comment here.

**Comment by erasmospunk** [comment]
The only thing that needs to change is the p2sh address from 5 to 16 (and all the versions on testnet).

BIP44 version "5" was submitted by me so Coinomi uses the correct index. BIP32 is not used but good to know in case we support importing BIP32 seeds.

Do you know when the new version with the updated p2sh version will be released?

Thanks for the updates!

**Comment by vertoe** [comment]
This was introduced in darkcoin core version 0.11.0.0 and was backported to all versions after 0.10.17.25. I posted a "heads-up" here: https://darkcointalk.org/threads/onyx-v3-10-17.3141/page-7#post-36037

So everyone using 0.10.17.25 and later is already seeing the new address version. Thanks for the comments on BIP44 :)

Does Coinomi support Trezor hardware storage by the way? I got told they use BIP44 implementations.

**Comment by erasmospunk** [comment]
Yes and no. If you take a Trezor seed it will work on Coinomi (Bitcoin only and only the first account) and vice versa. It doesn't support direct integration yet and for Darkcoin support it needs a modified firmware.

The good news is that Satoshi labs are friendly and from my talks with them, it is something that could be done in the future.

**Comment by erasmospunk** [comment]
The prefixes are updated. Thanks for reporting!

**Comment by vertoe** [comment]
:+1:
