### ISSUE TITLE
Q.R. code puzzle

### ISSUE THREAD

**Issue by shawnpringle** [Coinomi/coinomi-android#41]
Please see http://canada.host-ed.me/qrbitcoin.html

**Comment by erasmospunk** [comment]
The python version has a new line character '\n' in the end of the URI.

I will fix it in Coinomi by just calling String.trim() on the input but generally speaking it doesn't work with some wallets I tried.

**Comment by shawnpringle** [comment]
Someone should submit an issue for python qr.  Can you recommend an
alternative to taking screenshots of a wallet?
