### ISSUE TITLE
Question... on ShapeShift

### ISSUE THREAD

**Issue by geopayme** [Coinomi/coinomi-android#46]
On you outline details to release app, what do you mean Setup ShapeShift? - The ACRA part I go. 

-->setup ACRA and ShapeShift

**Comment by erasmospunk** [comment]
It is to set the Coinomi affiliate key, for tests builds it is not necessary.

**Comment by geopayme** [comment]
How is this API Key located? Its good to know!

**Comment by geopayme** [comment]
Also can you elaborate some in this section? Does it offer a Pair Ticker Value parsed from ShapeShift?

    private static final String BASE_URL = "https://ticker.coinomi.net/simple";
    private static final String TO_LOCAL_URL = BASE_URL + "/to-local/%s";
    private static final String TO_CRYPTO_URL = BASE_URL + "/to-crypto/%s";
    private static final String COINOMI_SOURCE = "coinomi.com";

**Comment by geopayme** [comment]
Worked it... thanks...
