### ISSUE TITLE
Restore my wallet and I have a problem 

### ISSUE THREAD

**Issue by mick93** [Coinomi/coinomi-android#48]
My funds on my previous a dress not appear I see 0 and all my funds are send on one adresse before I restore despite they change after all transaction I keep one adresse to receive my funds and now I restore my wallet I see one adresse but not the previous adresse with the funds

**Comment by GeorgeKimionis** [comment]
Ticket opened in Support, closing this issue.

**Comment by mick93** [comment]
In my wallet precede i had several address because every transaction avai I a new address, but the funds were always at the first address litecoin Red corner dogecoin digibyte and then i returned I can not find my money or the address avai I used

Envoyé depuis Yahoo Mail pour Android

De:"George Kimionis" <notifications@github.com>
Date:dim j août PM à 23:49
Objet:Re: [coinomi-android] Restore my wallet and I have a problem (#48)

Ticket opened in Support, closing this issue.

**Comment by mick93** [comment]
In my wallet precede i had several address because every transaction avai I a new address, but the funds were always at the first address litecoin Red corner dogecoin digibyte and then i returned I can not find my money or the address avai I used

Envoyé depuis Yahoo Mail pour Android

De:"George Kimionis" <notifications@github.com>
Date:dim j août PM à 23:49
Objet:Re: [coinomi-android] Restore my wallet and I have a problem (#48)

Closed #48.
