### ISSUE TITLE
custom fee

### ISSUE THREAD

**Issue by riX2000** [Coinomi/coinomi-android#52]
It would be nice to be able to set a custom fee when sending, and also a default fee in settings.
During one of the "stress tests" I experienced transactions not being included in several blocks.

**Comment by clacke** [comment]
At the moment the only transactions going through are the ones with a fee 5-10 times higher than the default 0.0001 BTC. I have a transaction that has been stuck for hours. This feature is becoming essential.

Maybe the wallet should even report the average fee from the latest couple of blocks to give an idea or even a default.

**Comment by erasmospunk** [comment]
From v1.6.0 it is possible to set custom fees in the Settings. Probably in future versions we will add dynamic fees in addition to the custom fees.
