### ISSUE TITLE
Seed restores bitcoin wallet but not dash

### ISSUE THREAD

**Issue by hammetje** [Coinomi/coinomi-android#54]
Dear support, 

I have tried to recover my wallet but my dash coins attached to that account don't show up. My bitcoins do. 

Also I can see the previous adresses list of my bitcoin wallet but my dash wallet doesn't show my previous adresses.

On the blockchain explorer the dash coins have not moved. What can I do to gain acces to my dash coins again?

**Comment by galimi** [comment]
I am having the same problem.
Have been successfully sending/receiving Dash for most of the day and it just stopped working a few hours ago.

**Comment by erasmospunk** [comment]
It was transient issue with our Dash nodes, probably due to a protocol update.
