### ISSUE TITLE
btc rejected transaction is still in the list of transactions and also used for the total sum in my wallet

### ISSUE THREAD

**Issue by sjabow** [Coinomi/coinomi-android#56]
I had an incoming transaction that got rejected with reason:
non-canonical signature: High S Value.

This transaction is now still showing up in my balance overview, and amount is also summed to my total.

this is for v1.5.22

**Comment by erasmospunk** [comment]
If you press the menu button and Refresh, does it still appear?

**Comment by sjabow** [comment]
No, it solved itself after a few days. 
Sorry should have come back on that.
But its very confusing, since it shows an incorrect balance all that time.

Not sure if its possible to filter these rejects out of the pending transactions.
