### ISSUE TITLE
Restoring Wallet to new phone does not reflect any coin

### ISSUE THREAD

**Issue by HendrikWi** [Coinomi/coinomi-android#65]
Hi,

I restored my Coinomi on another phone using the pass phrase and although the restore seems to be going through fine. There are no transactions and all the wallet balances are set to 0. 

Please could you let me know how I can get this restore working. I also tried to transfer some Dogecoin "99" but it says that I don't have enough money. Is there a limit as to how much I can transfer.

Looking forward to your reply.

Cheers!!

**Comment by erasmospunk** [comment]
Hello Hendrik, sorry for the late reply. For issues it is better to send and email to support at coinomi.com

It seems that you have enabled BIP39 password protection, make sure when you restore to select the BIP39 option and use password you used.
