### ISSUE TITLE
Nushare TXs not appearing

### ISSUE THREAD

**Issue by weeeee** [Coinomi/coinomi-android#67]
Two NSR TXs not showing, I used a new address for each TX.   

Coinomi v1.5.22
Android 5.0.2

Both of the wallet addresses displayed in Coinomi match the block explorer info below. I was able to receive NBT coins, but the wallet doesnt show any NSR transactions

63 NSR sent to SUedbB1Jxdg3eh9uS6edLPjoyBVqfkvmmc

https://explorer.coinpayments.net/transaction.php?chain=17&hash=87328ac851dcde6ece55a0318849c2bc2b0dbab9eda89dbdb250ec1f08c9fa9e

998 NSR sent to Sg1x8d5nkVvLM51fBm5zu6QPmtEwqRXjpX. 

https://explorer.coinpayments.net/transaction.php?chain=17&hash=3d385acb6b80eb430f1ea166a822ece6a0e2a4a18f4ffd99bab689c2e3cad010

**Comment by weeeee** [comment]
I uninstalled, reinstalled and recovered with the seed. My NBT coins are there but still no NSR coins in the wallet.

I'd like to be able to recover the private keys if possible. I cant find a wallet generator that can generate a HD wallet for NSR

**Comment by weeeee** [comment]
both transactions appeared in my wallet today

**Comment by erasmospunk** [comment]
Getting back to you. There was an issue with the electrum server.

There [this tool](https://coinomi.com/recovery-phrase-tool.html) to recover the private keys from seed but it currently does not have NSR.
