### ISSUE TITLE
Support for Guldencoin

### ISSUE THREAD

**Issue by Redsandro** [Coinomi/coinomi-android#69]
[Guldencoin](https://bitcointalk.org/index.php?topic=554412.0) (NLG) is just another Scrypt coin. I would love to see this one implemented, but the process seems to be a bit too technical for me to just do and offer pr.

* How do we get  an electrum server running the Guldencoin chain? Does coinomi have this server, or does every coin provide their own?
* Some coins have `BIP44` and others have `BIP39` mentioned in the code?
* How do we get NLG on [the BIP44 list](https://github.com/satoshilabs/docs/blob/master/slips/slip-0044.rst) for `bip44Index` if it requires a BIP44 wallet? (Chicken and egg)
* What is `unitExponent`?

**Comment by mjmacleod** [comment]
https://github.com/Coinomi/coinomi-android/pull/84

**Comment by Redsandro** [comment]
Great work @mjmacleod!
Please take a look @erasmospunk. This is a very welcome pr indeed.

**Comment by erasmospunk** [comment]
added! https://github.com/Coinomi/coinomi-android/commit/9bed9f936ccc3befb2942572d5a52795124dc432
