### ISSUE TITLE
Ability to add read-only "watcher" wallets

### ISSUE THREAD

**Issue by RichyHBM** [Coinomi/coinomi-android#71]
Given the security risks and ease of having your phone stolen/snooped it is sometimes not possible to use your phone as a wallet and instead you may require to have your actual wallet in cold storage/somewhere else. In these occasions it is still useful to be able to see how many coins you own.

It would be great to be able to scan a public key for a wallet in Coinomi and have it display its total amount and its current value.

**Comment by GeorgeKimionis** [comment]
Thank you for your suggestion, watch-only will be supported in one of the upcoming releases.
