### ISSUE TITLE
Any status update on the iOS version?

### ISSUE THREAD

**Issue by jgeewax** [Coinomi/coinomi-android#72]
I have lots of friends with iPhones who are in need of a safe and reliable wallet... I recommended Coinomi and got back the typical "Not for iOS yet :(" message.

Any chance you have some ETA on the iOS app ? I love Coinomi for Android

**Comment by GeorgeKimionis** [comment]
Thank you for recommending Coinomi to your friends, we will let you know as soon as there is an update on the iOS version.
