### ISSUE TITLE
Support for NXT

### ISSUE THREAD

**Issue by Jzarecta** [Coinomi/coinomi-android#74]
Wonder if its possible to add support for NXT, since this is a Proof of Stake coin, it might be a bit different. I would love to know if there are any technical difficulties to support them.

**Comment by GeorgeKimionis** [comment]
NXT will be supported in a future release.

**Comment by Jzarecta** [comment]
Sounds awesome.

On Tue, Mar 8, 2016 at 6:37 PM, George Kimionis <notifications@github.com>
wrote:

> NXT will be supported in a future release.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Coinomi/coinomi-android/issues/74#issuecomment-194025500>
> .
>



-- 
Alexandro Colorado
Apache OpenOffice Contributor
9060 55AB FFD2 2F02 0E1A  3409 599C 14FC 9450 D3CF
