### ISSUE TITLE
BlackCoin message signing or verification doesn’t work

### ISSUE THREAD

**Issue by KrzysiekJ** [Coinomi/coinomi-android#76]
Steps to reproduce:

1. Go into “Sign/verify message” screen inside BlackCoin wallet.
2. Paste a BlackCoin address from the wallet in the “signing address” field.
3. Enter some text in the “message” field.
4. Tap “Sign”.
5. Tap “Verify”.

What happens:
A statement “Message verification failed” is displayed.

What should happen:
A statement “Message verified” should be displayed.

Tested on Coinomi for Android v1.5.22.

**Comment by erasmospunk** [comment]
We just fixed it in the upcoming v1.6.0, you can try it out by enabling the beta channel: https://play.google.com/apps/testing/com.coinomi.wallet

**Comment by KrzysiekJ** [comment]
It seems to work, thanks!
