### ISSUE TITLE
Recover passphrase

### ISSUE THREAD

**Issue by Jzarecta** [Coinomi/coinomi-android#82]
I have a working wallet, but I am not sure if its possible to recover or generate a new passphrase. I am sure I backup my passphrase but I am not able remember where. Settings dont show anything regarding passphrase so I wonde r if I can do it somewhere else.

I am not lockout yet of the wallet, but want to make sure i got the right backups or renew the backups. Also wonder how to get my private keys for my wallets. 

Thanks.

**Comment by GeorgeKimionis** [comment]
Please forward your issue to: support@coinomi.com, the `Issues` board is for wallet-related issues only.

**Comment by Jzarecta** [comment]
Thanks I got the url for the tool for BIP 044. Althought only for a few
coins, I cant get other coins like Rubycoin, DOGE or DASH.

On Tue, Mar 8, 2016 at 6:32 PM, George Kimionis <notifications@github.com>
wrote:

> Please forward your issue to: support@coinomi.com, the Issues board is
> for wallet-related issues only.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Coinomi/coinomi-android/issues/82#issuecomment-194023142>
> .
>



-- 
Alexandro Colorado
Apache OpenOffice Contributor
9060 55AB FFD2 2F02 0E1A  3409 599C 14FC 9450 D3CF
