### ISSUE TITLE
Exchange rate statement is ambiguous

### ISSUE THREAD

**Issue by joepanther** [Coinomi/coinomi-android#85]
On the Exchange screen we see:

- Given rate includes ShapeShift.io transaction fee.

Most users will interpret this to mean that the rate includes only a ShapeShift.io transaction fee and no other transaction fee. A minority will interpret it to mean that there might be other fees in addition to a fee from ShapeShift.io.

It would be better to say some thing like one of the following:

- Given rate includes transaction fees, including one from ShapeShift.io.
- Given rate includes ShapeShift.io and other transaction fees.

**Comment by GeorgeKimionis** [comment]
Thanks for your suggestion, our UX specialist will look into it.
